# Generated by Django 2.1.3 on 2019-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_feed',
            name='name',
            field=models.CharField(default='dsads', max_length=20),
            preserve_default=False,
        ),
    ]
